name: Deploy to GCP bucket static file assets

on:
  push:
    branches:
    - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up GCP CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Deploy to GCP
      run: |
        gsutil -m rsync -r ./index.html gs://arvingai.com


    
